# Generated by Django 4.2.1 on 2023-06-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_search_date_search_amenity_filters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='address',
            new_name='city',
        ),
    ]
