# Generated by Django 4.2.1 on 2023-06-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, null=True)),
                ('places', models.JSONField(default=dict)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.marker'),
        ),
    ]
