# Generated by Django 4.2.1 on 2023-06-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='paths',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
