# Generated by Django 4.2.1 on 2023-06-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_path_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='query',
            field=models.JSONField(default=list),
        ),
    ]
