COLORS = [
    "red",
    "blue",
    "green",
    "purple",
    "orange",
    "darkred",
    "lightred",
    "beige",
    "darkblue",
    "darkgreen",
    "cadetblue",
    "darkpurple",
    "white",
    "pink",
    "lightblue",
    "lightgreen",
    "gray",
    "black",
    "lightgray",
]
COLOR_DICT = {
    "*": "blue",
    "apartment": "green",
    "aquarium": "purple",
    "arts_centre": "orange",
    "artwork": "darkred",
    "atm": "lightred",
    "attraction": "beige",
    "bank": "darkblue",
    "bar": "darkgreen",
    "bicycle_rental": "cadetblue",
    "biergarten": "darkpurple",
    "boat_rental": "white",
    "bus_station": "pink",
    "cafe": "lightblue",
    "car_rental": "lightgreen",
    "casino": "gray",
    "charging_station": "black",
    "cinema": "lightgray",
    "fast_food": "blue",
    "ferry_terminal": "green",
    "food_court": "purple",
    "fountain": "orange",
    "fuel": "darkred",
    "gallery": "lightred",
    "hospital": "beige",
    "hotel": "darkblue",
    "ice_cream": "darkgreen",
    "information": "cadetblue",
    "library": "darkpurple",
    "marketplace": "white",
    "motel": "pink",
    "museum": "lightblue",
    "nightclub": "lightgreen",
    "parking": "gray",
    "picnic_site": "black",
    "pub": "lightgray",
    "restaurant": "blue",
    "taxi": "green",
    "theatre": "purple",
    "theme_park": "orange",
    "toilets": "darkred",
    "townhall": "lightred",
    "viewpoint": "beige",
    "zoo": "darkblue",
}


HOME = "Home"
MAX_POPUP_WIDTH = 200

LEGEND_HTML = """<div style="position: fixed; bottom: 10px; left: 10px; z-index: 1000; background-color: white; padding: 10px; border-radius: 5px; border: 1px solid gray;"><h4>Legend</h4><ul style="list-style-type: none; padding: 0; margin: 0;">"""
